name: CI

on:
    pull_request:
      branches: ["main"]
      types: [opened, synchronize, reopened]

jobs:
  test:
    name: 'Node.js Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test